type: http
name: Trigger an automation run for a given suite and environment
url: '{{baseUrl}}/test-runs'
method: POST
headers:
  - key: Content-Type
    value: application/json
  - key: Accept
    value: application/json
body:
  type: json
  content: |-
    {
      "suiteId": "a418b668-5e81-2120-4895-b555c290de2b",
      "environment": "dev",
      "releaseVersion": "string",
      "triggeredBy": "string",
      "runMode": "regression"
    }
examples:
  - response:
      statusCode: 201
      statusText: Created
      body:
        type: json
        content: |-
          {
            "runId": "0df6c4b2-9181-16f4-41fb-7c627a815053",
            "suiteId": "1b27967b-1d2a-c464-e1b2-943a0827f342",
            "status": "queued",
            "environment": "string",
            "releaseVersion": "string",
            "startedAt": "2018-09-30T16:31:47.039Z",
            "finishedAt": "1976-01-01T18:32:59.400Z",
            "passedCount": 1351,
            "failedCount": 740,
            "flakyCount": 3091
          }
      headers:
        - key: Content-Type
          value: application/json
    name: Test run started
