type: http
name: Trigger an automation run for a given suite and environment
url: '{{baseUrl}}/test-runs'
method: POST
headers:
  - key: Content-Type
    value: application/json
  - key: Accept
    value: application/json
body:
  type: json
  content: |-
    {
      "suiteId": "a88214a1-07aa-7416-dff6-6fed7af98058",
      "environment": "qa",
      "releaseVersion": "string",
      "triggeredBy": "string",
      "runMode": "full"
    }
examples:
  - response:
      statusCode: 201
      statusText: Created
      body:
        type: json
        content: |-
          {
            "runId": "f861a5cd-3ef8-6d12-0856-112026b267fd",
            "suiteId": "9b705604-4b6d-6148-fec7-4b5e379c8bcd",
            "status": "passed",
            "environment": "string",
            "releaseVersion": "string",
            "startedAt": "2010-10-21T18:08:37.927Z",
            "finishedAt": "1988-09-12T07:16:46.686Z",
            "passedCount": 8740,
            "failedCount": 7503,
            "flakyCount": 8715
          }
      headers:
        - key: Content-Type
          value: application/json
    name: Test run started
