type: http
name: Trigger an automation run for a given suite and environment
url: '{{baseUrl}}/test-runs'
method: POST
headers:
  - key: Content-Type
    value: application/json
  - key: Accept
    value: application/json
body:
  type: json
  content: |-
    {
      "suiteId": "7635f6e5-ecaa-3619-50c8-9185f6396a53",
      "environment": "preprod",
      "releaseVersion": "string",
      "triggeredBy": "string",
      "runMode": "full"
    }
examples:
  - response:
      statusCode: 201
      statusText: Created
      body:
        type: json
        content: |-
          {
            "runId": "86e9a8ee-bf2b-42ed-9dda-f1fb36bf44b5",
            "suiteId": "275e1006-3dc2-aeae-e0e0-8c09b9178f1c",
            "status": "cancelled",
            "environment": "string",
            "releaseVersion": "string",
            "startedAt": "1962-06-19T00:09:59.794Z",
            "finishedAt": "2021-08-01T10:22:30.643Z",
            "passedCount": 8775,
            "failedCount": 1953,
            "flakyCount": 6169
          }
      headers:
        - key: Content-Type
          value: application/json
    name: Test run started
